export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const FETCH_PROFILE = "FETCH_PROFILE";
export const FETCH_MOVIE = "FETCH_MOVIE";
export const FETCH_COLLECTION = "FETCH_COLLECTION";
export const CHANGE_COLLECTION_NAME = "CHANGE_COLLECTION_NAME";
export const MOVIE_RATING = "MOVIE_RATING";
